config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }

  root to: "application#index"

  resources :extratos, only: [:index, :new, :create]
end

app/models/extrato.rb
class Extrato < ActiveRecord::Base
  
  belongs_to :tipo_operacao
  belongs_to :conta, validate: true, autosave: true

  belongs_to :nova_conta, class_name: "Conta", validate: true, autosave: true

  accepts_nested_attributes_for :conta, :nova_conta

  delegate :nome, :prefixo, :metodo, to: :tipo_operacao, prefix: true

  attr_accessor :conta_transferencia_id, :transferencia_recebida
  # toda operação possui extrato, portanto as operações serão incluídas neste model

  # valida valores negativos
  validates_numericality_of :valor, greater_than_or_equal_to: 0
  # valida se a nova conta existe
  validates_presence_of :nova_conta, message: "precisa ser válida", :if => Proc.new{ |f| f.tipo_operacao.metodo == "transferencia" }

  # processa o tipo de operação
  before_validation :processa_operacao

  # ordena por ordem de criação
  default_scope { order('created_at desc') }
  
  def valor_index
    "#{tipo_operacao_prefixo}#{valor}"
  end

  def processa_operacao
    send(tipo_operacao_metodo)
  end

  # depósito
  def deposito
    self.conta.saldo += valor
  end

  # saque
  def saque
    self.conta.saldo -= valor
  end

  # transferência
  def transferencia
    # taxa de transferência
    if valor > 1000
      taxa = 10
    elsif ![0,6].include?(Time.now.wday) && (Time.now.hour >= 9 && Time.now.hour < 18)
      taxa = 5
    else
      taxa = 7
    end
    
    # remove da conta atual
    self.conta.saldo -= valor+taxa
    self.descricao = "Transferência para a conta #{nova_conta.try(:id)} taxa de #{taxa}"

    # nova conta recebe transferência
    self.nova_conta.extratos.new({
      tipo_operacao_id: TipoOperacao.where(metodo: "recebe_transferencia").take.id,
      conta_transferencia_id: self.id,
      valor: valor,
    }) if nova_conta
  end

  # receber transferência
  def recebe_transferencia
    
    if !transferencia_recebida
    self.conta.saldo += self.valor
    self.descricao = "Transferência da conta #{self.conta_transferencia_id}"
    self.transferencia_recebida = true
    end
  end

end

app/controllers/extratos_controller.rb
class ExtratosController < ApplicationController


  def index
    @filtro = ExtratoFiltro.new(params[:extrato_filtro] || {})
    
    @extratos = Extrato.includes(:tipo_operacao).where(
      conta_id: current_user.conta_id
    )

    puts @filtro.data_inicio

    if @filtro.valid? && params[:extrato_filtro]
      @extratos = @extratos.where(["created_at between ? and ?", @filtro.data_inicio.as_date, @filtro.data_fim.as_date])
    end
  end

  # GET /extratos/new
  def new
    @extrato = Extrato.new(tipo_operacao_id: params[:tipo_operacao_id])
  end

  def create
    @extrato = Extrato.new(extrato_params.merge(conta_id: current_user.conta_id))
    
    respond_to do |format|
      if @extrato.save
        format.html { redirect_to new_extrato_path(tipo_operacao_id: @extrato.tipo_operacao_id) , notice: "#{@extrato.tipo_operacao_nome} efetuado(a)" }
      else
        format.html { render :new }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extrato
      @extrato = Extrato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def extrato_params
      params[:extrato].permit(:valor, :tipo_operacao_id, :nova_conta_id)
    end
end

app/helpers/extratos_helper.rb
module ExtratosHelper
end

app/views/extratos/_form.html.slim
= form_for @extrato do |f|
  - if @extrato.errors.any?
    #error_explanation
      h2 = "#{pluralize(@extrato.errors.count, "erro")}:"
      ul
        - @extrato.errors.full_messages.each do |message|
          li = message

  = f.hidden_field :tipo_operacao_id, value: @extrato.tipo_operacao_id

  - if @extrato.tipo_operacao.metodo == "transferencia"
    .field
      = f.label :nova_conta
      br
      = f.number_field :nova_conta_id
  .field
    = f.label :valor
    br
    = f.number_field :valor


  .actions = f.submit value: "Enviar"

app/views/extratos/index.html.slim
h3 Extrato

h4 Filtro de data
= form_for @filtro, url: extratos_path, method: :get do |f|
  - if @filtro.errors.any?
    #error_explanation
      h2 = "#{pluralize(@filtro.errors.count, "erro")}:"
      ul
        - @filtro.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :data_inicio
    br
    = f.text_field :data_inicio
  .field
    = f.label :data_fim
    br
    = f.text_field :data_fim

  .actions = f.submit :enviar

table style="margin-top: 50px;"
  thead
    tr
      th Data
      th Operação
      th Descrição
      th Valor

  tbody
    - @extratos.each do |extrato|
      tr
        td = l extrato.created_at
        td = extrato.tipo_operacao_nome
        td = extrato.descricao
        td = extrato.valor_index

app/views/extratos/new.html.slim
h3 #{@extrato.tipo_operacao.nome}

= render 'form'